baseURL = "https://blog.lame.host/"
languageCode = "en-us"
title = "notes"
theme = "simple-hugo-theme"
copyright = "Â© 2019 - bostrt - All rights reserved."

# Highlighting
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "vs"

# Taxonomies
[taxonomies]
#  tag = "tags"
#  category = "categories"

# Menu
[menu]
  # Header
  [[menu.main]]
    url = "/post/"
    name = "blog"
    weight = 1
  [[menu.main]]
    url = "/about/"
    name = "about"
    weight = 2

  # Footer
  [[menu.footer]]
    url = "https://github.com/bostrt"
    name = "GitHub"
    weight = 1
  [[menu.footer]]
    url = "/post/index.xml"
    name = "RSS"
    weight = 2

# Links format
[permalinks]
  post = "/post/:year/:month/:title/"

[params]
  # Date format (default: Jan 2, 2006)
# datefmt  = "Jan 2, 2006"
